"""New addition

Revision ID: 922897c3c898
Revises: a7ca1fcb943c
Create Date: 2025-08-31 22:25:23.291599

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922897c3c898'
down_revision: Union[str, Sequence[str], None] = 'a7ca1fcb943c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_appliances', sa.Column('bill_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_user_appliances_bill_id'), 'user_appliances', ['bill_id'], unique=False)
    op.create_foreign_key(None, 'user_appliances', 'bills', ['bill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_appliances', type_='foreignkey')
    op.drop_index(op.f('ix_user_appliances_bill_id'), table_name='user_appliances')
    op.drop_column('user_appliances', 'bill_id')
    # ### end Alembic commands ###
