"""Add role to User model

Revision ID: a7ca1fcb943c
Revises: f90d0ab0f78c
Create Date: 2025-08-24 22:50:26.430671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # <-- Make sure sqlmodel is imported


# revision identifiers, used by Alembic.
revision: str = 'a7ca1fcb943c'
down_revision: Union[str, Sequence[str], None] = 'f90d0ab0f78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --- ADD THIS: Define the ENUM type for use in the script ---
userrole_enum = sa.Enum('USER', 'ADMIN', name='userrole')
# -----------------------------------------------------------


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- ADD THIS LINE: Create the ENUM type in the database FIRST ---
    userrole_enum.create(op.get_bind(), checkfirst=True)
    # ---------------------------------------------------------------

    op.add_column('users', sa.Column('role', userrole_enum, nullable=False, server_default='USER'))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')

    # --- ADD THIS LINE: Drop the ENUM type from the database LAST ---
    userrole_enum.drop(op.get_bind())
    # --------------------------------------------------------------
    
    # ### end Alembic commands ###