# """Add cascade deletes to relationships

# Revision ID: adcf34458771
# Revises: dedfb3e3a8a1
# Create Date: 2025-09-16 19:22:29.944862

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'adcf34458771'
# down_revision: Union[str, Sequence[str], None] = 'dedfb3e3a8a1'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     pass
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     pass
#     # ### end Alembic commands ###

"""Add cascade deletes to relationships

Revision ID: adcf34458771
Revises: dedfb3e3a8a1
Create Date: 2025-09-16 19:22:29.944862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adcf34458771"
down_revision: Union[str, None] = "dedfb3e3a8a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to add cascade delete for appliance estimates."""
    # First, drop the existing foreign key constraint
    op.drop_constraint(
        "appliance_estimates_user_appliance_id_fkey",
        "appliance_estimates",
        type_="foreignkey",
    )

    # Then, create a new foreign key constraint with ON DELETE CASCADE
    op.create_foreign_key(
        "appliance_estimates_user_appliance_id_fkey",  # Constraint name
        "appliance_estimates",  # Source table
        "user_appliances",  # Target table
        ["user_appliance_id"],  # Local columns
        ["id"],  # Remote columns
        ondelete="CASCADE",  # This enables cascading deletes
    )


def downgrade() -> None:
    """Downgrade schema to remove cascade delete."""
    # To downgrade, we do the reverse: drop the CASCADE constraint
    op.drop_constraint(
        "appliance_estimates_user_appliance_id_fkey",
        "appliance_estimates",
        type_="foreignkey",
    )

    # And re-create the original constraint without the CASCADE rule
    op.create_foreign_key(
        "appliance_estimates_user_appliance_id_fkey",
        "appliance_estimates",
        "user_appliances",
        ["user_appliance_id"],
        ["id"],
    )
