"""fix star_rating column to integer

Revision ID: dedfb3e3a8a1
Revises: 922897c3c898
Create Date: 2025-08-31 22:47:49.715490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dedfb3e3a8a1"
down_revision: Union[str, Sequence[str], None] = "922897c3c898"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_appliances",
        "star_rating",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using="star_rating::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_appliances",
        "star_rating",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
